name: Build
run-name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image_variant:
          - "mainn"
          - "fips"
          - "native"

    steps:
      - name: Checkout source @ ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output image tag
        id: image_tag
        run: |
          echo "IMAGE_TAG=${{ format('{0}{1}{2}', '1.0.0', matrix.image_variant == 'mainn' && '' || '-', matrix.image_variant == 'mainn' && '' || matrix.image_variant) }}" >> "$GITHUB_OUTPUT"

      - name: Run build
        run: |
            echo $IMAGE_TAG
