name: Release
run-name: release with pull request
on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches:
      - main
      - maintenance-*
      - migration-*
      - rc-*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'schedule' && 'main' || '' }}
          fetch-depth: 0
          filter: blob:none
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Match label for version bump
        id: bump
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: ${{ github.ref_name == 'main' && 'major, minor, patch' || (startsWith(github.ref_name, 'maintenance-') && 'minor, patch' || 'patch') }}
          default_match: patch

      - name: Tag new version
        id: tag
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          per_branch: ${{ (startsWith(github.ref_name, 'migration-') || startsWith(github.ref_name, 'rc-')) && true || false }}
          dry_run: true

#      - name: Release new version
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag.outputs.version_tag }}
#          generateReleaseNotes: true
#          token: ${{ steps.app-token.outputs.token }}
