name: repository-dispatch
run-name: Dispatch Repository Event - build-published

on:
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Build version to integrate'
        required: true
        default: 'latest'
      build_repository:
        description: 'Build repository to integrate'
        required: true
        default: 'gha-scratch-pad1'

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  dispatch-repository-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: rubel-ahammad/gha-integration
          event-type: build-published
          client-payload: |
            {
              "build_version": "${{ github.event.inputs.build_version }}",
              "build_repository": "${{ github.event.inputs.build_repository }}"
            }
